import { StyleSheet, View } from "react-native";
import { router } from "expo-router";
import { CompanionMascot, MASCOT_LABELS } from "@/components/CompanionMascot";
import { PixelMascot } from "@/components/PixelMascot";
import { RouteErrorBoundary } from "@/components/ErrorBoundary";
import { Card } from "@/components/ui/Card";
import { ChoiceChip } from "@/components/ui/ChoiceChip";
import { NexusButton } from "@/components/ui/NexusButton";
import { NexusText } from "@/components/ui/NexusText";
import { Screen } from "@/components/ui/Screen";
import { useNexus } from "@/providers/NexusProvider";
import type { DashboardPreferences, DashboardSection, ThemeId } from "@/types";

export { RouteErrorBoundary as ErrorBoundary };

const SECTION_LABELS: Record<DashboardSection, string> = { smart: "Nexus inteligente", mission: "Missão principal", tasks: "Tarefas", operation: "Operação", habits: "Hábitos", quick: "Ações rápidas", progress: "Progresso", message: "Ordem do Nexus" };
const PRESETS: { id: DashboardPreferences["preset"]; label: string; description: string; sections: DashboardSection[]; hidden: DashboardSection[] }[] = [
  { id: "original", label: "Nexus Original", description: "Equilíbrio entre missão, tarefas e progresso", sections: ["smart","mission","tasks","quick","progress","operation","habits","message"], hidden: [] },
  { id: "minimal", label: "Minimalista", description: "Somente o essencial para hoje", sections: ["mission","tasks","progress","message","smart","quick","operation","habits"], hidden: ["operation","habits","quick"] },
  { id: "productivity", label: "Produtividade", description: "Tarefas e atalhos primeiro", sections: ["smart","tasks","quick","mission","habits","progress","operation","message"], hidden: [] },
  { id: "gamer", label: "Gamer", description: "Desafios, operação e telemetria em destaque", sections: ["smart","operation","progress","mission","tasks","habits","quick","message"], hidden: [] },
  { id: "focus_first", label: "Focus First", description: "Missão e entrada no foco sem ruído", sections: ["mission","quick","smart","tasks","progress","operation","habits","message"], hidden: ["habits"] },
  { id: "progress_first", label: "Progress First", description: "Métricas antes do plano", sections: ["progress","smart","mission","tasks","operation","habits","quick","message"], hidden: [] },
  { id: "compact", label: "Compacto", description: "Mais informação em menos espaço", sections: ["mission","tasks","smart","progress","quick","operation","habits","message"], hidden: ["message"] },
  { id: "cinematic", label: "Cinemático", description: "Missão, operação e brilho visual", sections: ["smart","mission","operation","tasks","progress","quick","habits","message"], hidden: [] },
];
const THEMES: [ThemeId, string, string][] = [["nexus","Nexus Purple","#8B5CF6"],["amoled","AMOLED","#9B7BFF"],["oneui","One UI Future","#7C9CFF"],["hud","Mission HUD","#2DD4A8"],["aurora","Aurora","#22D3EE"],["ocean","Deep Ocean","#38BDF8"],["ember","Ember","#F97316"],["rose","Rose Protocol","#EC4899"],["monochrome","Monochrome","#E4E4E7"]];

export default function CustomizeScreen() {
  const { data, colors, updatePreferences } = useNexus();
  const dashboard = data.preferences.dashboard;
  const applyPreset = (preset: typeof PRESETS[number]) => updatePreferences({ dashboard: { preset: preset.id, sections: preset.sections, hiddenSections: preset.hidden } });
  const move = (section: DashboardSection, direction: -1 | 1) => { const list = [...dashboard.sections]; const index = list.indexOf(section); const target = index + direction; if (index < 0 || target < 0 || target >= list.length) return; [list[index], list[target]] = [list[target]!, list[index]!]; updatePreferences({ dashboard: { sections: list, preset: "custom" } }); };
  const toggleHidden = (section: DashboardSection) => updatePreferences({ dashboard: { hiddenSections: dashboard.hiddenSections.includes(section) ? dashboard.hiddenSections.filter((item) => item !== section) : [...dashboard.hiddenSections, section], preset: "custom" } });
  return <Screen>
    <View style={styles.header}><NexusButton label="Voltar" variant="ghost" onPress={() => router.back()} /><View style={styles.flex}><NexusText variant="mono" color={colors.primarySoft}>COMMAND CENTER</NexusText><NexusText variant="display">Do seu jeito.</NexusText></View><CompanionMascot mascot={data.preferences.mascot.companion} size={58} /></View>
    <Section title="Layouts" subtitle="Comece por um estilo e ajuste cada módulo depois."><View style={styles.grid}>{PRESETS.map((preset) => <Card key={preset.id} style={[styles.preset, { borderColor: dashboard.preset === preset.id ? colors.primary : colors.border }]}><NexusText variant="title">{preset.label}</NexusText><NexusText variant="caption" secondary>{preset.description}</NexusText><NexusButton label={dashboard.preset === preset.id ? "Ativo" : "Aplicar"} variant={dashboard.preset === preset.id ? "secondary" : "ghost"} onPress={() => applyPreset(preset)} fullWidth /></Card>)}</View></Section>
    <Section title="Ordem e visibilidade" subtitle="Mova, esconda e recupere qualquer módulo.">{dashboard.sections.map((section, index) => { const hidden = dashboard.hiddenSections.includes(section); return <Card key={section} style={[styles.sectionRow, { opacity: hidden ? 0.55 : 1 }]}><View style={styles.flex}><NexusText variant="subtitle">{SECTION_LABELS[section]}</NexusText><NexusText variant="caption" secondary>{hidden ? "Oculto" : `Posição ${index + 1}`}</NexusText></View><View style={styles.rowActions}><NexusButton label="↑" variant="ghost" onPress={() => move(section, -1)} /><NexusButton label="↓" variant="ghost" onPress={() => move(section, 1)} /><NexusButton label={hidden ? "Mostrar" : "Ocultar"} variant="ghost" onPress={() => toggleHidden(section)} /></View></Card>; })}</Section>
    <Section title="Densidade e efeitos"><Choice title="Densidade" options={[["compacta","Compacta"],["confortavel","Confortável"],["ampla","Ampla"]]} value={dashboard.density} onChange={(value) => updatePreferences({ dashboard: { density: value as DashboardPreferences["density"] } })} /><Choice title="Brilho" options={[["desligado","Desligado"],["sutil","Sutil"],["medio","Médio"],["intenso","Intenso"]]} value={dashboard.glow} onChange={(value) => updatePreferences({ dashboard: { glow: value as DashboardPreferences["glow"] } })} /><Choice title="Fundo" options={[["nenhum","Limpo"],["grade","Grade"],["estrelas","Estrelas"],["aurora","Aurora"],["scanlines","Scanlines"]]} value={dashboard.backgroundEffect} onChange={(value) => updatePreferences({ dashboard: { backgroundEffect: value as DashboardPreferences["backgroundEffect"] } })} /></Section>
    <Section title="Temas"><View style={styles.grid}>{THEMES.map(([id,label,color]) => <Card key={id} style={[styles.theme, { borderColor: data.preferences.theme === id ? color : colors.border }]}><View style={[styles.color, { backgroundColor: color }]} /><NexusText variant="subtitle">{label}</NexusText><NexusButton label={data.preferences.theme === id ? "Ativo" : "Usar"} variant="ghost" onPress={() => updatePreferences({ theme: id })} /></Card>)}</View></Section>
    <Section title="Companheiro" subtitle="Nexus continua sendo o mascote principal."><View style={styles.grid}>{(["atlas","nova","byte","pulse"] as const).map((mascot) => <Card key={mascot} style={[styles.mascot, { borderColor: data.preferences.mascot.companion === mascot ? colors.primary : colors.border }]}><CompanionMascot mascot={mascot} size={62} /><NexusText variant="subtitle">{MASCOT_LABELS[mascot]}</NexusText><NexusButton label={data.preferences.mascot.companion === mascot ? "Ativo" : "Escolher"} variant="ghost" onPress={() => updatePreferences({ mascot: { companion: mascot, showCompanion: true } })} /></Card>)}</View></Section>
    <Section title="Visuais do Professor Atlas" subtitle="Óculos continuam; você escolhe a cor da cobrinha professora no app e no widget."><View style={styles.grid}>{([['classic','Clássico'],['emerald','Esmeralda'],['gold','Dourado'],['ice','Gelo'],['rose','Rose']] as const).map(([variant, label]) => <Card key={variant} style={[styles.mascot, { borderColor: data.preferences.mascot.professorVariant === variant ? colors.primary : colors.border }]}><CompanionMascot mascot="atlas" variant={variant} size={62} /><NexusText variant="subtitle">{label}</NexusText><NexusButton label={data.preferences.mascot.professorVariant === variant ? "Ativo" : "Usar"} variant="ghost" onPress={() => updatePreferences({ mascot: { professorVariant: variant } })} /></Card>)}</View></Section>
    <Section title="Skins da cobrinha Nexus" subtitle="A skin também acompanha o widget."><View style={styles.grid}>{data.preferences.mascot.unlockedSkins.map((skin) => <Card key={skin} style={[styles.mascot, { borderColor: data.preferences.mascot.skin === skin ? colors.primary : colors.border }]}><PixelMascot skin={skin} accessory={skin === "professor" ? "glasses" : ""} size={62} /><NexusText variant="subtitle">{{ classic: "Clássica", shadow: "Shadow", galaxy: "Galaxy", emerald: "Emerald", gold: "Gold", ice: "Ice", rose: "Rose", professor: "Professor" }[skin]}</NexusText><NexusButton label={data.preferences.mascot.skin === skin ? "Ativa" : "Usar"} variant="ghost" onPress={() => updatePreferences({ mascot: { skin } })} /></Card>)}</View></Section>
    <Section title="Acessórios" subtitle="Combine com qualquer skin."><View style={styles.chips}><ChoiceChip label="Nenhum" selected={!data.preferences.mascot.equippedAccessory} onPress={() => updatePreferences({ mascot: { equippedAccessory: undefined } })} />{data.preferences.mascot.accessories.map((accessory) => <ChoiceChip key={accessory} label={{ glasses: "Óculos", crown: "Coroa", headphones: "Headset", cap: "Boné", scarf: "Cachecol" }[accessory] ?? accessory} selected={data.preferences.mascot.equippedAccessory === accessory} onPress={() => updatePreferences({ mascot: { equippedAccessory: accessory } })} />)}</View></Section>
  </Screen>;
}

function Section({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) { return <View style={styles.section}><View style={styles.title}><NexusText variant="title">{title}</NexusText>{subtitle ? <NexusText variant="caption" secondary>{subtitle}</NexusText> : null}</View>{children}</View>; }
function Choice({ title, options, value, onChange }: { title: string; options: [string,string][]; value: string; onChange: (value: string) => void }) { return <View style={styles.choice}><NexusText variant="caption" secondary>{title}</NexusText><View style={styles.chips}>{options.map(([id,label]) => <ChoiceChip key={id} label={label} selected={value === id} onPress={() => onChange(id)} />)}</View></View>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 12 }, flex: { flex: 1 }, section: { marginTop: 28, gap: 13 }, title: { gap: 4 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 9 }, preset: { width: "48%", flexGrow: 1, minHeight: 166, gap: 9 }, sectionRow: { flexDirection: "row", alignItems: "center", gap: 9 }, rowActions: { flexDirection: "row", alignItems: "center", gap: 3 }, choice: { gap: 8 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, theme: { width: "31%", minWidth: 104, flexGrow: 1, alignItems: "center", gap: 8 }, color: { width: 34, height: 34, borderRadius: 12 }, mascot: { width: "48%", flexGrow: 1, alignItems: "center", gap: 8 } });
